export const IMAGES = {
    banner_mobileimg: "banner_mobile.jpg",
    bannerimg: "Hero.jpg",
    camera_img: "Group+1261155236.svg",
    icon: "icon/",
    about_img: "video-cam.png",
    login_sidebar_banner: "ozolio_circle.png",
    live_streamgraphic_01: "Live+stream.svg",
    live_stream: "live_stream.png",
    logo_main: "logo_main.8ad3dee0.png",
    logo_main_svg: "logo_main.svg",
    logo_main1_svg: "logo_main1.svg",
    logo_mob_1_svg: "logo_mob_1.svg",
    logo_mob_svg: "logo_mob.svg",
    logo: "logo.png",
    next_svg: "next.svg",
    Passport_1: "Passport-1.jpg",
    repost_img: "repost-img.png",
    tokenomics: "tokenomics.png",
    uploads: "uploads/",
    vercel_svg: "vercel.svg",
    videoimg: "videoimg.png",
    White_paper_02: "whitepaper.png",
    Why_Invest_Cam: "ozolio_Cam.png"
}

export const ICONS = {
    about_img: "icon/about_img.png",
    arrow: "icon/arrow.svg",
    cross_icon: "icon/cross_icon.svg",
    do_icon: "icon/do_icon.svg",
    experts_icon: "icon/experts_icon.svg",
    fb_icon: "icon/fb_icon.svg",
    market_icon: "icon/market_icon.svg",
    plus_icon: "icon/plus_icon.svg",
    plusicon: "icon/plusicon.png",
    strong_icon: "icon/strong_icon.svg",
    telegram_icon: "icon/telegram_icon.svg",
    tiktok_icon: "icon/tiktok_icon.svg",
    uparrow: "icon/uparrow.svg",
    utility_icon: "icon/utility_icon.svg",
    Whitepapaer_img: "icon/Whitepapaer_img.png",
    youtube_icon: "icon/youtube_icon.svg"
};
